apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod
spec:
  containers:
  - name: pytorch-phy5
    image: gitlab-registry.nautilus.optiputer.net/yueyujiang/nautilus_tutorial:test1
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 8Gi
        cpu: "2"
      requests:
        memory: 8Gi
        cpu: "2"
    volumeMounts:
      - name: mydata
        mountPath: /mnt/myscratch
  volumes:
    - name: mydata
      emptyDir: {}
  restartPolicy: Never
