apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod-storage
spec:
  containers:
  - name: pytorch-phy5
    image: gitlab-registry.nautilus.optiputer.net/yueyujiang/nautilus_tutorial/build_tree:v1
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - name: documents
      mountPath: /documents
    - name: data
      mountPath: /data
    resources:
      limits:
        memory: 8Gi
        cpu: "2"
      requests:
        memory: 8Gi
        cpu: "2"
  volumes:
    - name: documents
      persistentVolumeClaim:
        claimName: vol2
    - name: data
      persistentVolumeClaim:
        claimName: vol1
  restartPolicy: Never
